using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyInformationalVersionAttribute("1.0.17.7")]
[assembly: AssemblyFileVersionAttribute("1.0.17.7")]
[assembly: AssemblyVersionAttribute("1.0.17.7")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2010, Abundant Closet LLC")]
[assembly: AssemblyCompanyAttribute("Abundant Closet LLC")]
[assembly: AssemblyTrademarkAttribute("Trademark by Abundant Closet LLC")]
[assembly: AssemblyConfigurationAttribute("release")]

