ALTER TABLE registereduser
 DROP FOREIGN KEY FK34E1D74B3BBCEB6C,
 DROP FOREIGN KEY FK34E1D74B396708F6,
 ADD CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER Channel;
ALTER TABLE registereduser
 ADD CONSTRAINT FK34E1D74B3BBCEB6C FOREIGN KEY (SizeId) REFERENCES usersizes (UserSizeId) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK34E1D74B396708F6 FOREIGN KEY (BasicUserId) REFERENCES basicusers (BasicUserId) ON UPDATE RESTRICT ON DELETE RESTRICT;
 
 
ALTER TABLE closetgarments
 DROP FOREIGN KEY FK2B6CBC66977BA838,
 DROP FOREIGN KEY FK2B6CBC664741FB3A,
 DROP FOREIGN KEY FK2B6CBC669C8FDEBF,
 ADD CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER Status;
ALTER TABLE closetgarments
 ADD CONSTRAINT FK2B6CBC66977BA838 FOREIGN KEY (GarmentId) REFERENCES garments (GarmentId) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK2B6CBC664741FB3A FOREIGN KEY (DetailsId) REFERENCES garmentdetails (GarmentDetailsId) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK2B6CBC669C8FDEBF FOREIGN KEY (ClosetId) REFERENCES closets (ClosetId) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE closets
 ADD CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER CreationStatus;

ALTER TABLE garmentdetails
 ADD CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER StoreConditions;

ALTER TABLE garments
 DROP FOREIGN KEY garments_ibfk_1,
 DROP FOREIGN KEY garments_ibfk_2,
 DROP FOREIGN KEY garments_ibfk_3,
 DROP FOREIGN KEY garments_ibfk_4,
 DROP FOREIGN KEY garments_ibfk_5,
 ADD CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER Keywords;
ALTER TABLE garments
 ADD CONSTRAINT garments_ibfk_1 FOREIGN KEY (SilouhetteId) REFERENCES silouhettes (SilouhetteId) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT garments_ibfk_2 FOREIGN KEY (PatternId) REFERENCES patterns (PatternId) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT garments_ibfk_3 FOREIGN KEY (FabricId) REFERENCES fabrics (FabricId) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT garments_ibfk_4 FOREIGN KEY (PreGarmentId) REFERENCES pregarments (pregarmentid) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT garments_ibfk_5 FOREIGN KEY (DefaultColorId) REFERENCES colors (ColorId) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE invitationcodes
 DROP FOREIGN KEY invitationcodes_ibfk_1,
 ADD CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER IsUsed;
ALTER TABLE invitationcodes
 ADD CONSTRAINT invitationcodes_ibfk_1 FOREIGN KEY (InvitedById) REFERENCES basicusers (BasicUserId) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE inviteduser
 DROP FOREIGN KEY inviteduser_ibfk_1,
 ADD CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER EmailAddressReplaced;
ALTER TABLE inviteduser
 ADD CONSTRAINT inviteduser_ibfk_1 FOREIGN KEY (BasicUserId) REFERENCES basicusers (BasicUserId) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE outfitdetails
 ADD CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER ClosetOutfitId;

ALTER TABLE outfitupdaters
 DROP FOREIGN KEY partner,
 DROP FOREIGN KEY silouhettes,
 DROP FOREIGN KEY patterns,
 DROP FOREIGN KEY colorfamily,
 ADD CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER Status;
ALTER TABLE outfitupdaters
 ADD CONSTRAINT partner FOREIGN KEY (PartnerId) REFERENCES partners (PartnerId) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT silouhettes FOREIGN KEY (SilouhetteId) REFERENCES silouhettes (SilouhetteId) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT patterns FOREIGN KEY (PatternId) REFERENCES patterns (PatternId) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT colorfamily FOREIGN KEY (ColorFamilyId) REFERENCES colorfamilies (ColorFamilyId) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE trackingoutfitsupdaters
 ADD CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER ClosetOutfitId;
